version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: cplh_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: clph
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

  backend:
    build: .
    container_name: cplh_backend
    ports:
      - "4000:4000"
    volumes:
      - ../frontend/public/pending-resources:/app/frontend/public/pending-resources
      - ../frontend/public/class-cards:/app/frontend/public/class-cards
    environment:
      NODE_ENV: production

volumes:
  db_data:
