version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: cplh_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: clph
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro

volumes:
  db_data:
